[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
cargo-audit = "0.17.4"
cargo-tarpaulin = "0.25.1"
cargo-watch = "8.4.0"
